kind: pipeline
type: docker
name: default

steps:
  - name: greeting
    image: node
    commands:
      - echo "Greeting"
      - npm i -g typescript
      - tsc --version
  - name: morning
    image: node
    commands:
      - tsc --version
